.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Virtual Machine Administrator Login" -ElevationDuration PT1H -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Desktop Virtualization Reader" -ElevationDuration PT1H -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Desktop Virtualization contributor" -ElevationDuration PT1H -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Desktop Virtualization power on off contributor" -ElevationDuration PT1H -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Reader" -ElevationDuration PT1H -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Owner" -ElevationDuration PT1H -ApprovalGroups ("sg-azure-users-mg-m365-pim-approvers") -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "Contributor" -ElevationDuration PT1H -ApprovalGroups ("sg-azure-users-mg-m365-pim-approvers") -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive
.\Set-AzurePIMRoleSettings.ps1 -ResourceType ManagementGroup -ResourceName "test" -TenantName tucson.onmicrosoft.us -Roles "User Access Administrator" -ElevationDuration PT1H -ApprovalGroups ("sg-azure-users-mg-m365-pim-approvers") -RequireAuthContext -Notification_Admin_EndUser_Assignment $notificationEmails -allowpermanentactive



.\Add-AzureRole-PIMElegibility.ps1 -ResourceType subscription -RoleName "Desktop Virtualization Contributor" -ResourceName "m365-AVD-Dev" -TenantName tucson.onmicrosoft.us -Group sg-azure-users-mg-m365-sub-avd-desktop-virtualization-contributor
disconnect-mggraph
.\Add-AzureRole-PIMElegibility.ps1 -ResourceType subscription -RoleName "Desktop Virtualization Contributor" -ResourceName "m365-AVD-Dev" -TenantName tucson.onmicrosoft.us -Group sg-azure-users-mg-m365-sub-avd-desktop-virtualization-contributor
.\Add-AzureRole-PIMElegibility.ps1 -ResourceType subscription -RoleName "Desktop Virtualization Reader" -ResourceName "m365-AVD-Dev" -TenantName tucson.onmicrosoft.us -Group sg-azure-users-mg-m365-sub-avd-desktop-virtualization-reader
.\Add-AzureRole-PIMElegibility.ps1 -ResourceType subscription -RoleName "Desktop Virtualization Power On Off Contributor" -ResourceName "m365-AVD-Dev" -TenantName tucson.onmicrosoft.us -Group sg-azure-users-mg-m365-sub-avd-desktop-virtualization-power-on-off-contributor
